import 'normalize.css'
import './style.css'
import '../../assets/styles/general.css'
import '../../assets/images/bamboo-cap.jpg'
import '../../assets/images/flower_foto1.png'
import '../../assets/images/pets-1.jpg'
import '../../assets/images/pets2.jpg'
import '../../assets/images/pets3.jpg'
import '../../assets/images/pets4.jpg'
import '../../assets/images/pets5.jpg'
import '../../assets/images/pets6.jpg'
import '../../assets/images/flower_foto1.png'
import '../../assets/images/palm_foto.png'
import '../../assets/images/user2.jpg'
import '../../assets/images/user3.jpg'
import '../../assets/images/user4.jpg'
import '../../assets/icons/banana-bamboo_icon.svg'
import '../../assets/icons/arrow.svg'
import '../../assets/icons/card.svg'
import '../../assets/icons/zoo.svg'
import '../../assets/icons/monkey.svg'
import '../../assets/icons/user_icon.svg'
import '../../assets/icons/fb-logo.svg'
import '../../assets/icons/instagram.svg'
import '../../assets/icons/twitter.svg'
import '../../assets/icons/youtube.svg'
import '../../assets/icons/meet-fish_icon.svg'

console.log('Отступ слева в футтере на 1000px - ошибка макета, за это не снижается, написано в задании.')
console.log('Внутри среднего отзыва также ошибка макета.')