import 'normalize.css'
import './style.css'
import '../../assets/styles/general.css'
import '../../assets/images/bamboo-cap.jpg'
import '../../assets/images/flower_foto1.png'
import '../../assets/images/pets-1.jpg'
import '../../assets/images/pets2.jpg'
import '../../assets/images/pets3.jpg'
import '../../assets/images/pets4.jpg'
import '../../assets/images/pets5.jpg'
import '../../assets/images/pets6.jpg'
import '../../assets/images/flower_foto1.png'
import '../../assets/images/palm_foto.png'
import '../../assets/images/user2.jpg'
import '../../assets/images/user3.jpg'
import '../../assets/images/user4.jpg'
import '../../assets/icons/banana-bamboo_icon.svg'
import '../../assets/icons/arrow.svg'
import '../../assets/icons/card.svg'
import '../../assets/icons/zoo.svg'
import '../../assets/icons/monkey.svg'
import '../../assets/icons/user_icon.svg'
import '../../assets/icons/fb-logo.svg'
import '../../assets/icons/instagram.svg'
import '../../assets/icons/twitter.svg'
import '../../assets/icons/youtube.svg'
import '../../assets/icons/meet-fish_icon.svg'


console.log('Расхождение с макетом в установленных рамках (10 и 20px в зависимости от места расхождения)')
console.log('После блока Pets (со слайдером и картинками) нужно установить отступ Y -110 в расширении Perfect Pixel')